AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API Gateway deployment with SAM
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-deployment/93291ef7811692344a47f40a8ad8e01c
      Handler: get.handler
      Runtime: nodejs8.10
      Events:
        GetRoot:
          Type: Api
          Properties:
            RestApiId:
              Ref: MyApi
            Path: /books
            Method: get
